# Компилятор C++
CXX = g++

# -O2: уровень оптимизации 2 для повышения производительности
CXXFLAGS = -std=c++11 -O2

SRCS = threadpool.cpp

HEADERS = Header.h

# Список объектных файлов, соответствующих исходным
# Заменяем расширение .cpp на .o(под линукс)
OBJS = $(SRCS:.cpp=.o)

# Создаваемый файл, его имя
TARGET = result

all: $(TARGET)

# Правило для сборки исполняемого файла из объектных файлов
$(TARGET): $(OBJS)
 $(CXX) $(CXXFLAGS) -o $@ $^

# Правило для компиляции каждого исходного файла в объектный файл
%.o: %.cpp $(HEADERS)
 $(CXX) $(CXXFLAGS) -c $<

clean:
 rm -f $(OBJS)
 rm -f ./result

.PHONY: all clean